// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240714131707_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Noice",
                            Created = new DateTime(2024, 7, 14, 6, 17, 7, 64, DateTimeKind.Local).AddTicks(7982),
                            Title = "Went Hiking with Joe"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Noce",
                            Created = new DateTime(2024, 7, 14, 6, 17, 7, 64, DateTimeKind.Local).AddTicks(7985),
                            Title = "Went Hiking wh Joe"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Noce",
                            Created = new DateTime(2024, 7, 14, 6, 17, 7, 64, DateTimeKind.Local).AddTicks(7988),
                            Title = "C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
